# Generated by Django 2.1.1 on 2018-09-12 20:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HostelBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HostelMess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MessName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OutingForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_no', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='Registation number should be like 17BCE1007', regex='\\d{2}[a-zA-Z]{3}\\d{4}')])),
                ('name', models.CharField(max_length=100)),
                ('mess_type', models.CharField(max_length=100)),
                ('student_phone_number', models.CharField(default='', max_length=13, validators=[django.core.validators.RegexValidator(message='Phone number should be up to 10 digits only', regex='^\\d{10}$')])),
                ('parent_phone_number', models.CharField(default='', max_length=13, validators=[django.core.validators.RegexValidator(message='Phone number should be up to 10 digits only', regex='^\\d{10}$')])),
                ('date_of_outing', models.DateField(null=True)),
                ('time_of_leaving', models.TimeField()),
                ('time_of_arrival', models.TimeField()),
                ('viiting_address', models.TextField()),
                ('purpose_of_leaving', models.CharField(max_length=250)),
                ('permanent_address', models.TextField()),
                ('is_approved', models.BooleanField(default=False)),
                ('hostel_block', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ov.HostelBlock')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('registration_no', models.CharField(max_length=9, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Plese give valid registration number', regex='\\d{2}[a-zA-Z]{3}\\d{4}')])),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='visibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outing_form', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Warden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostelblock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ov.HostelBlock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
