# Generated by Django 2.1.1 on 2018-09-12 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ov', '0002_auto_20180913_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warden',
            name='hostelblock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ov.HostelBlock'),
        ),
        migrations.AlterField(
            model_name='warden',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
