# Generated by Django 2.1.1 on 2018-09-19 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ov', '0004_filter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filter',
            name='date_of_outing',
        ),
    ]
