# Generated by Django 2.1.1 on 2018-09-19 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ov', '0005_remove_filter_date_of_outing'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='date_of_outing',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
